# This is a basic workflow to help you get started with Actions

name: auto_update


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: setup python
        with: 
          python-version: '3.8.x'
      - name: updates data files
        run: python DataClean.py
      - name: Commit updates
        run: |
          git config --global user.name 'Abi Shalom'
          git config --global user.email 'abishalom@gmail.com'
          git commit -am  "Data update"
          git push
